### ISSUE TITLE
[BUG]  "Install a plugin" button does not open up the file manager under Linux

### ISSUE THREAD

**Issue by Dizobo** [BlackPearlOrigin/blackpearlorigin#21]
**What bug did you encounter?**<br>
Please provide a clear and concise description of the bug.
The "Install a plugin" button does not open the file manager to select a downloaded plugin zip file

**Please provide the steps to reproduce the bug.**<br>
1. Open BPO AppImage on Linux
2. Click on Preferences
3. Navigate to Plugins
4. Click on "Install a plugin"
5. Nothing Happens

**What did you expect to happen?**<br>
Expected BPO to open the file manager and allow the user to select the plugin zip file.

**Please specify your operating system and its version.**<br>
 - OS: Arch Linux
 - Version: 6.4.4-arch1-1

**Comment by mantasx1001** [comment]
This issue is on all OSes
for linux put plugins in local/share/io.github.blackpearlorigin/plugins

**Comment by Brisolo32** [comment]
Fixed on #22
