### ISSUE TITLE
[BUG] Please update version number in releases.

### ISSUE THREAD

**Issue by dataprolet** [BlackPearlOrigin/blackpearlorigin#30]
Please add the actual version number to the package, it's still 0.3.0. Otherwise I can't update the binaries AUR-package: _black-pearl-origin_0.3.0_amd64.deb_.

**Comment by dataprolet** [comment]
Nevermind, I could update the package just fine. It would be still nice to have the actual version number in the releases files.

**Comment by Brisolo32** [comment]
Yeah, on the next release we're gonna update this, since it needs to be bumped so the updater can work
